# Generated by Django 3.0 on 2022-10-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serial',
            name='budget',
            field=models.PositiveIntegerField(default='неизвестно'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='fees',
            field=models.PositiveIntegerField(default='неизвестно'),
        ),
    ]
