# Generated by Django 3.0 on 2022-10-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0002_auto_20221001_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serial',
            name='budget',
            field=models.PositiveIntegerField(default='$'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='fees',
            field=models.PositiveIntegerField(default='$'),
        ),
    ]
